# Generated by Django 4.0.3 on 2022-04-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('W', 'WORK'), ('S', 'SCHOOL'), ('P', 'PERSONAL')], max_length=10)),
            ],
            options={
                'ordering': ['completed'],
            },
        ),
    ]
