# Generated by Django 4.0.3 on 2022-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Work', 'WORK'), ('School', 'SCHOOL'), ('Personal', 'PERSONAL')], max_length=10),
        ),
    ]
