# Generated by Django 4.0.3 on 2022-04-05 05:26

from django.db import migrations, models
#import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=75)),
                ('phone_number', models.IntegerField(blank=True, max_length=31)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='collaborators',
            field=models.ManyToManyField(to='main_app.collaborator'),
        ),
    ]
