# Generated by Django 4.0.3 on 2022-04-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_task_event_event_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main_app.event'),
        ),
    ]
