# Generated by Django 4.0.4 on 2022-04-12 00:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(regex='(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{4})')]),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
